### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by kanitw** [altair-viz/jupyterlab_voyager#39]
I suspect that this is a Jupyter problem.

```
jupyter labextension install jupyterlab_voyager
> /usr/local/bin/npm pack jupyterlab_voyager
jupyterlab_voyager-0.1.0.tgz

Errored, use --debug for full output:
AttributeError: full_url
```

Adding --`debug` give the following result 

```
 jupyter labextension install jupyterlab_voyager --debug                          ⏎
Searching [u'/Users/kanitw', '/Users/kanitw/.jupyter', '/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/etc/jupyter
Looking for jupyter_config in /Users/kanitw/.jupyter
Looking for jupyter_config in /Users/kanitw
> /usr/local/bin/npm pack jupyterlab_voyager
jupyterlab_voyager-0.1.0.tgz
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 71, in start
    ans = self.run_task()

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 227, in install_extension
    return handler.install_extension(extension)

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 366, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 1138, in _install_extension
    version = self._latest_compatible_package_version(name)

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 1202, in _latest_compatible_package_version
    metadata = _fetch_package_metadata(self.registry, name, self.logger)

  File "/usr/local/lib/python2.7/site-packages/jupyterlab/commands.py", line 1585, in _fetch_package_metadata
    logger.debug('Fetching URL: %s' % (req.full_url))

  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 254, in __getattr__
    raise AttributeError, attr

AttributeError: full_url


Errored, use --debug for full output:
AttributeError: full_url
```

**Comment by memory-yancy** [comment]
@kanitw Similar error in my situation, how to resolve it ?  Thanks in advanced .

**Comment by hfcredidio** [comment]
I had a similar problem, and updating jupyterlab solved it.

**Comment by rickystream94** [comment]
@kanitw Did you manage to solve the issue? I have JupyterLab version 0.32.1-py27_0 and I'm experiencing it when trying to install whatever extension
