### ISSUE TITLE
Support jupyterlab 1.1.3

### ISSUE THREAD

**Issue by josemarfdc** [altair-viz/jupyterlab_voyager#77]
I'm having a weird error. It says jupyterlab_voyager supports a newer version of jupyter lab, but I have the latest version of jupyterlab (1.1.3)

See error below
```bash
Node v11.10.0

> /home/ubuntu/anaconda3/envs/JupyterHub/bin/npm pack jupyterlab_voyager
npm notice 
npm notice 📦  jupyterlab_voyager@1.0.2
npm notice === Tarball Contents === 
npm notice 1.9kB  package.json                         
npm notice 1.5kB  LICENSE                              
npm notice 2.8kB  README.md                            
npm notice 913B   lib/index.d.ts                       
npm notice 28.8kB lib/index.js                         
npm notice 439B   lib/tutorial.d.ts                    
npm notice 979B   lib/tutorial.js                      
npm notice 4.5kB  lib/voyagerpanel.d.ts                
npm notice 28.9kB lib/voyagerpanel.js                  
npm notice 3.3kB  style/Images/download (1).png        
npm notice 21.8kB style/Images/ExportIcon.png          
npm notice 1.4kB  style/Images/ExportToNotebookIcon.png
npm notice 323B   style/Images/RedoIcon.svg            
npm notice 311B   style/Images/SaveIcon.svg            
npm notice 309B   style/Images/UndoIcon.svg            
npm notice 9.1kB  style/Images/VoyagerIcon.png         
npm notice 2.3kB  style/index.css                      
npm notice 604B   style/variables.css                  
npm notice 3.2kB  tutorial/tutorial.md                 
npm notice === Tarball Details === 
npm notice name:          jupyterlab_voyager                      
npm notice version:       1.0.2                                   
npm notice filename:      jupyterlab_voyager-1.0.2.tgz            
npm notice package size:  53.1 kB                                 
npm notice unpacked size: 113.5 kB                                
npm notice shasum:        a44da9b9b65cfe0c6a2290df47fce4ddf5b50c40
npm notice integrity:     sha512-2E4sdtvcdGz6r[...]0MqFd0CAYo/bA==
npm notice total files:   19                                      
npm notice 
jupyterlab_voyager-1.0.2.tgz

Fetching URL: https://registry.npmjs.org/jupyterlab_voyager
Fetching URL: https://registry.npmjs.org/jupyterlab_voyager
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/envs/JupyterHub/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/ubuntu/anaconda3/envs/JupyterHub/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/home/ubuntu/anaconda3/envs/JupyterHub/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/home/ubuntu/anaconda3/envs/JupyterHub/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/home/ubuntu/anaconda3/envs/JupyterHub/lib/python3.7/site-packages/jupyterlab/commands.py", line 321, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/ubuntu/anaconda3/envs/JupyterHub/lib/python3.7/site-packages/jupyterlab/commands.py", line 525, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/home/ubuntu/anaconda3/envs/JupyterHub/lib/python3.7/site-packages/jupyterlab/commands.py", line 1450, in _install_extension
    raise ValueError(msg)

ValueError: No version of jupyterlab_voyager could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLabExtension        Package
>=16.8.4 <16.9.0>=16.9.0 <17.0.0 react
>=16.8.4 <16.9.0>=16.9.0 <17.0.0 react-dom

Exiting application: jupyter
```

**Comment by playermanny2** [comment]
@josemarfdc i plan on updating to support 1.1.3 soon

**Comment by Zireael** [comment]
Latest  version of Jupyterlab is 1.2.0 (29 Oct 19)
https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html

Does Voyager need to be pinned to a specific JupyterLab version and updated by hand each time?

Im getting error:

```
Step 63/111 : RUN jupyter labextension install --no-build jupyterlab_voyager
 ---> Running in 7a28e5467fa6
An error occured.
ValueError: No version of jupyterlab_voyager could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLabExtension        Package
>=16.8.4 <16.9.0>=16.9.0 <17.0.0 react
>=16.8.4 <16.9.0>=16.9.0 <17.0.0 react-dom
See the log file for details:  /tmp/jupyterlab-debug-12w9r5js.log
ERROR: Service 'jupyterlab' failed to build: The command '/bin/bash -c jupyter labextension install --no-build jupyterlab_voyager' returned a non-zero code: 1
```

**Comment by MostafaGazar** [comment]
Last time I tried, I managed to get it working with a couple years old Jupyter lab image where the react versions matched, there might a better way to get it working!

**Comment by wookayin** [comment]
Using jupyterlab 1.2.4 which is the latest as of 2020/1/12. Still the same error. I don't think this jupyterlab extension is installable by anyone. Seems this software is not well maintained.

**Comment by ghost** [comment]
Upstream datavoyager needs to be ported to react 16, currently uses 15.
See https://github.com/altair-viz/jupyterlab_voyager/issues/82#issuecomment-811743066
